# site name
prefixName: Dynamic_Pigeon の
siteName: 秘密小屋
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: https://cdn.luogu.com.cn/upload/usericon/545317.png
url: https://chy669086.github.io
description: Live your life with passion! With some drive!
cdn: 
pjax: 1
# 1开启
mathjax: 1

notice: hexo-Sakura主题已经开源，目前正在开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    题解: {path: /categories/题解/, fa: fa-file-text-o }, 
    # 生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    # 资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    # 随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    # 歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://s3.bmp.ovh/imgs/2024/10/01/7d1f2d8f10653936.png
  - https://s3.bmp.ovh/imgs/2024/10/01/d254935c80511b82.png
  - https://s3.bmp.ovh/imgs/2024/10/01/fff584855710b2ee.png
  - https://s3.bmp.ovh/imgs/2024/10/01/8e3255ed13b6619b.png
  - https://s3.bmp.ovh/imgs/2024/10/01/ed194d2571726fcb.png
  - https://s3.bmp.ovh/imgs/2024/10/01/89a65a3569f8a057.png
  - http://cdnjson.com/images/2024/10/01/81197b85969320adbdf325c260404543.png
  - http://cdnjson.com/images/2024/10/01/bb00ebdf0be26ef8765361f1184fa2a0.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: https://s3.bmp.ovh/imgs/2024/10/01/edd0bbedddebf15d.png}
  # - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  # - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 10/01/2024

#social  url, img PC端配置
social:
  github: {url: http://github.com/chy669086, img: https://s3.bmp.ovh/imgs/2024/10/01/57ace9502880e6f2.png}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  # email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/chy669086, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  # qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: 
  alipay: /images/donate/AliPayQR.png
  wechat: /images/donate/WeChanQR.png
  wechatSQ: /images/donate/WeChanQR.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: UBcI72jTU9rI7JRLoMf8dDYW-MdYXbMMI
v_appKey: gTKs1SNQSmReQkqrp7NTzcTK

# Waline
waline:
  enable: true
  serverURL: https://waline-5e8bt69qc-chy669086s-projects.vercel.app/ #服务端地址
  visitor: true #统计阅读量
  comment_count: true #统计评论数
  avatar: mp # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: 祝开开心心！ # Comment Box placeholder
  requiredFields: [ 'nick','mail' ] #设置必填项
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #输入框提示动画